;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=None
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="EnemyDamage.ApplyDamage",DevComment="")
+GameplayTagList=(Tag="EnemyDamage.Projectile.PassThrough",DevComment="")
+GameplayTagList=(Tag="PlayerDamage.Aggravate.Player",DevComment="")
+GameplayTagList=(Tag="PlayerDamage.Aggravate.Self",DevComment="")
+GameplayTagList=(Tag="PlayerDamage.Projectile.PassThrough",DevComment="")
+GameplayTagList=(Tag="PlayerDamage.Projectile.RecieveDamage",DevComment="")
+GameplayTagList=(Tag="Status.Prone",DevComment="")

