;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=None
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="PlayerDamage.Aggravate.Player",NewTagName="PlayerDamage.Enrage.Player")
+GameplayTagRedirects=(OldTagName="PlayerDamage.Aggravate.Self",NewTagName="PlayerDamage.Enrage.Self")
+GameplayTagRedirects=(OldTagName="PlayerDamage.Aggravate",NewTagName="PlayerDamage.Enrage")
+GameplayTagList=(Tag="EnemyDamage.ApplyDamage",DevComment="")
+GameplayTagList=(Tag="EnemyDamage.Projectile.PassThrough",DevComment="")
+GameplayTagList=(Tag="PlayerDamage.Enrage.Player",DevComment="")
+GameplayTagList=(Tag="PlayerDamage.Enrage.Self",DevComment="")
+GameplayTagList=(Tag="PlayerDamage.Projectile.PassThrough",DevComment="")
+GameplayTagList=(Tag="PlayerDamage.Projectile.RecieveDamage",DevComment="")
+GameplayTagList=(Tag="Status.Burning",DevComment="")
+GameplayTagList=(Tag="Status.Prone",DevComment="")
+GameplayTagList=(Tag="Status.Slowed",DevComment="")

